name = "PowerFlowData"
uuid = "dd99e9e3-7471-40fc-b48d-a10501125371"
authors = ["Nick Robinson <npr251@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
